name: Setup Python
description: Sets up Python version using Pyenv
author: Kristian Zarebski

inputs:
  python-version:
    description: Version of Python to install
    required: true
  use-poetry:
    description: Setup Python Poetry
    required: false
    default: ""
  setup-venv:
    description: Whether to setup a virtual environment
    required: false
    default: "false"
  requirements:
    description: Optional requirements file to install
    required: false
    default: ""
  poetry-args:
    description: Additional arguments to poetry install command
    required: false
    default: ""

runs:
  using: node16
  main: dist/index.js
