name: python3.12
on: [push]
jobs:
    build:
      name: Ubuntu (Python3.12)
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: artemis-beta/setup-python-pyenv@v0.1
          with:
            python-version: 3.12.1
            use-poetry: true
